apiVersion: v1
kind: Service
metadata:
  name: devopsjenk
  labels:
    app: ci-cd-app
spec:
  selector:
    app: first
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000
